spring.application.name=ai-task-manager
debug=false
server.port=8081
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO

spring.datasource.url=jdbc:h2:file:./data/tasks-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.cors.allowed-origin=http://localhost:5173
